[package]
name = "client"
version = "0.1.0"
authors = ["kaagarw"]

[dev-dependencies]
criterion = "0.2"

[dependencies]
openssl = {path = "/home/kaagarw/rust-openssl/openssl"}

[[bench]]
name = "tls_benchmark"
harness = false
